### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by exussum12** [FriendsOfTYPO3/phpstan-typo3#13]
hi

The licence suggests MIT composer suggests GPL2

could these by synced to the preferred licence

**Comment by bmack** [comment]
IMHO it should be GPL2+, but I need to check with all existing contributors to modify the license.

Anyway, great hint - thanks for that.

@lolli42 @ervaude @georgringer @alexanderschnitzler please ALL approve to decide for GPL2+ on the license of this package via a quick approval comment in this issue. so we can create a PR to replace the LICENSE file.

**Comment by alexanderschnitzler** [comment]
Sure, whatever suits best.

**Comment by georgringer** [comment]
Approved

**Comment by ervaude** [comment]
Approved

**Comment by lolli42** [comment]
Approved

**Comment by lolli42** [comment]
Hey. We'll sunset this repo in the forseeable future, it is nearly fully obsolete by now.
As such, we'll no longer apply a license change. I hope its ok to close here.
